title: Open Research Working Group Aberdeen
description: Researchers encouraging and supporting open research practices in Aberdeen, UK
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
